Repository TungTvPh81102/DATN-BE, pull requests merged in 2025-01, with the labels that each got.

#26 feature/course-api
  app/Http/Controllers/API/Auth/AuthController.php
  app/Http/Controllers/API/Auth/GoogleController.php
  app/Http/Controllers/API/Instructor/CourseController.php
  app/Http/Requests/API/Bases/BaseFormRequest.php
  app/Http/Requests/API/Courses/StoreCourseRequest.php
  app/Models/Course.php
  routes/api-v1.php
  routes/api-v2.php
  routes/api.php
  routes/web.php
Labels: feature

#27 refactor/admin-post-show-edit
  app/Http/Controllers/Admin/PostController.php
  app/Models/Post.php
  app/Models/User.php
  resources/views/posts/edit.blade.php
  resources/views/posts/show.blade.php
Labels: refactor

#29 feature/admin-post-list-create-destroy
  app/Http/Controllers/Admin/PostController.php
  app/Http/Requests/Admin/Categories/StoreCategoryRequest.php
  app/Http/Requests/Admin/Categories/UpdateCategoryRequest.php
  app/Http/Requests/Admin/Posts/StorePostRequest.php
  resources/views/categories/index.blade.php
  resources/views/posts/create.blade.php
  resources/views/posts/index.blade.php
Labels: feature

#30 Feature/admin profile role
  app/Http/Controllers/Admin/PostController.php
  app/Http/Controllers/Admin/RoleController.php
  resources/views/layouts/partials/topbar.blade.php
  resources/views/roles/profile.blade.php
  routes/web.php
Labels: ui

#34 feature/course-api
  app/Http/Controllers/API/Auth/AuthController.php
  app/Http/Controllers/API/Instructor/CourseController.php
  app/Http/Requests/API/Courses/UpdateContentCourse.php
  app/Models/Course.php
  app/Traits/UploadToCloudinaryTrait.php
  database/migrations/2025_01_03_084154_add_column_courses_table.php
  database/migrations/2025_01_03_215521_rename_requirement_to_requirements_in_courses_table.php
  routes/api.php
Labels: feature

#35 feature/chapter-api
  app/Http/Controllers/API/Instructor/ChapterController.php
  app/Http/Controllers/API/Instructor/CourseController.php
  app/Http/Kernel.php
  app/Http/Middleware/RoleHasInstructor.php
  app/Http/Requests/API/Chapters/StoreChapterRequest.php
  app/Http/Requests/API/Chapters/UpdateChapterRequest.php
  app/Http/Requests/API/Chapters/UpdateOrderChapterRequest.php
  app/Http/Requests/API/Users/SinginUserRequest.php
  app/Models/Chapter.php
  app/Models/Course.php
  app/Models/Lesson.php
  routes/api.php
Labels: feature

#37 add routes/api - fix conflict
  routes/api.php
Labels: bug

#38 feature/api-register-instructor
  app/Http/Controllers/API/Auth/AuthController.php
  app/Http/Controllers/API/Instructor/RegisterController.php
  app/Http/Controllers/API/Search/SearchController.php
  app/Http/Requests/API/Users/RegisterInstructorRequest.php
  app/Http/Requests/API/Users/SigninInstructorRequest.php
  routes/api.php
Labels: feature

#39 feature/api-forgot-reset-verify-password
  app/Http/Controllers/API/Auth/AuthController.php
  app/Http/Controllers/API/Posts/PostController.php
  app/Http/Requests/API/Auth/ForgotPassWordRequest.php
  app/Http/Requests/API/Auth/ResetPasswordRequest.php
  app/Http/Requests/API/Auth/VerifyEmailRequest.php
  routes/api.php
Labels: feature

#41 Feature/api-transaction
  app/Http/Controllers/API/Auth/AuthController.php
  app/Http/Controllers/API/Document/DocumentController.php
  app/Http/Controllers/API/Search/SearchController.php
  app/Http/Controllers/API/Transaction/TransactionController.php
  app/Http/Requests/API/Transaction/DepositTransactionRequest.php
  database/seeders/TransactionSeeder.php
  routes/api.php
Labels: feature
